[versions]

kotlin = "2.3.0"
ktor = "3.4.0"
logback = "1.5.31"
rabbitmq = "5.21.0"

[libraries]

# ktor
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor"}
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback"}

# rabbitmq
rabbitmq-amqp-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq" }

#test
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[bundles]
ktor-server = [
    "ktor-server-core-jvm",
    "ktor-server-netty",
    "ktor-server-core",
    "ktor-server-config-yaml",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }

